-- Semilla de Supabase (SPEC 06): los datos de ejemplo del sitio.
-- Generada una vez desde los JSON de src/data/; desde entonces los datos de ejemplo se editan aquí.
-- Se carga con `npx supabase db reset` en local y con `npx supabase db push --include-seed` en la nube.

insert into imagenes (ruta, ancho, alto) values
	('refugio/logo.jpg', 225, 225),
	('refugio/patio.jpg', 387, 516),
	('peludos/luna.jpg', 188, 269),
	('peludos/canelo.jpg', 194, 259),
	('campanas/cartel-2026-09-26.jpg', 820, 820);

insert into refugio (id, nombre, frase, ubicacion, direccion, latitud, longitud, enlace_mapa, messenger, logo_id, es_ejemplo) values
	('refugio', 'Ladridos de Esperanza', 'Un refugio que sale adelante gracias a personas como tú. Ayúdanos a esterilizar, dar en adopción y cuidar a los peludos que más lo necesitan.', 'Tenancingo, Estado de México', 'Calle de ejemplo 1, col. Centro', 18.9568545, -99.6010805, 'https://www.google.com/maps/place/Ladridos+Esperanza+Tenancingo/@18.9568545,-99.6036554,17z/data=!3m1!4b1!4m6!3m5!1s0x85cd9582bfab708f:0x1677173226f55379!8m2!3d18.9568545!4d-99.6010805!16s%2Fg%2F11g2yy8f2k', '100067644922613', (select id from imagenes where ruta = 'refugio/logo.jpg'), true);

insert into redes (id, red, etiqueta, url, orden, es_ejemplo) values
	('facebook', 'facebook', 'Facebook', 'https://www.facebook.com/ladridos.esperanza.5/', 1, false),
	('instagram', 'instagram', 'Instagram', 'https://www.instagram.com/ladridosdeesperanzatenancingo/', 2, false),
	('facebook-sos', 'facebook_sos', 'Facebook de SOS Ladridos de Esperanza Tenancingo', 'https://www.facebook.com/p/Sos-Ladridos-de-Esperanza-Tenancingo-100067644922613/', 3, false),
	('tiktok', 'tiktok', 'TikTok', 'https://www.tiktok.com/@sos_ladridostenancingo', 4, false);

insert into categorias (id, nombre, orden, es_ejemplo) values
	('cafeterias', 'Cafeterías', 1, true),
	('taquerias', 'Taquerías', 2, true),
	('comida-corrida', 'Comida corrida', 3, true),
	('panaderias', 'Panaderías', 4, true),
	('pizzas', 'Pizzas', 5, true);

insert into bloques_contenido (id, seccion, titulo, texto, orden, publicado, es_ejemplo) values
	('quienes-somos', 'quienes_somos', 'Quiénes somos', 'Somos el refugio Ladridos de Esperanza, en Tenancingo. Rescatamos perros y gatos, los cuidamos, los esterilizamos y les buscamos una familia. Aquí irá la historia real del refugio.', 1, true, true),
	('proceso-adopcion', 'proceso_adopcion', 'Cómo es el proceso de adopción', 'Escríbenos por Messenger con el nombre del peludo que te interesa.

Te contamos su historia y agendamos una visita al refugio.

Si es buena pareja para tu familia, firmamos juntos una carta de adopción responsable.', 1, true, true),
	('por-que-esterilizar', 'esterilizacion_por_que', 'Por qué esterilizar', 'Menos animales nacen sin un hogar que los espere.

Se cuida la salud de tu mascota.

Ayudas a toda la comunidad.', 1, true, true),
	('antes-de-la-cirugia', 'esterilizacion_cuidados', 'Antes de la cirugía', 'Texto de ejemplo. El veterinario del refugio indicará cuántas horas de ayuno necesita tu mascota y qué llevar el día de la campaña.', 1, true, true),
	('despues-de-la-cirugia', 'esterilizacion_cuidados', 'Después de la cirugía', 'Texto de ejemplo. El veterinario del refugio indicará los cuidados de la herida y cuándo puede volver a comer y jugar.', 2, true, true),
	('pregunta-edad', 'esterilizacion_preguntas', '¿Desde qué edad se puede esterilizar?', 'Respuesta de ejemplo. La confirma el veterinario del refugio.', 1, true, true),
	('pregunta-recuperacion', 'esterilizacion_preguntas', '¿Cuánto tarda en recuperarse?', 'Respuesta de ejemplo. La confirma el veterinario del refugio.', 2, true, true),
	('pregunta-reservar', 'esterilizacion_preguntas', '¿Necesito reservar mi lugar?', 'Sí. Los lugares son limitados y se apartan con el pago. Escríbenos por Messenger para reservar.', 3, true, true),
	('voluntariado', 'voluntariado', 'Voluntariado y hogar temporal', 'Mayores de 18 años, un sábado al mes.', 1, true, true);

insert into problematicas (id, titulo, texto, icono, etiqueta_cifra, cifra, fecha_cifra, fuente, orden, publicada, es_ejemplo, enlace_texto, enlace_url, enlace_sensible) values
	('abandono-y-maltrato', 'Abandono y maltrato', 'Llegan animales abandonados, heridos o desnutridos, y algunos casos terminan en denuncia. En julio de 2025 el refugio compartió en Facebook un caso de abandono y maltrato y presentó una denuncia ante la Fiscalía.', 'shield-alert', 'Rescates por año', '120', '2026-09-30', 'Registro del refugio', 1, true, true, 'Nota de prensa', 'https://www.posta.com.mx/edomex/hombre-arroja-a-perrito-a-jauria-que-lo-ataca-hasta-la-muerte-en-tenancingo-video/vl2062208', true),
	('sobrepoblacion', 'Sobrepoblación', 'Las camadas sin hogar llenan las calles y presionan a los refugios.', 'users', 'Animales que recibe al mes', '10', '2026-09-30', 'Registro del refugio', 2, true, true, null, null, null),
	('gastos-veterinarios', 'Gastos veterinarios', 'Vacunas, desparasitación, cirugías, medicinas y urgencias cuestan todo el año.', 'stethoscope', 'Gasto veterinario mensual', '$8,000', '2026-09-30', 'Registro del refugio', 3, true, true, null, null, null),
	('alimento-y-cuidados', 'Alimento y cuidados diarios', 'Comida, agua y limpieza, todos los días, sin descanso.', 'soup', 'Gasto mensual en alimento', '$12,000', '2026-09-30', 'Registro del refugio', 4, true, true, null, null, null),
	('espacio-limitado', 'Espacio limitado', 'Cada animal necesita espacio. Cuando el refugio se llena, no puede rescatar a más.', 'house', 'Capacidad y ocupación', '60 de 70 lugares', '2026-09-30', 'Registro del refugio', 5, true, true, null, null, null),
	('enfermedades-y-emergencias', 'Enfermedades y emergencias', 'Los animales enfermos o atropellados necesitan atención inmediata.', 'siren', 'Emergencias por año', '25', '2026-09-30', 'Registro del refugio', 6, true, true, null, null, null),
	('adopciones-lentas', 'Adopciones lentas', 'Muchos esperan meses o años por un hogar, y la adopción debe ser responsable para que no vuelvan.', 'hourglass', 'Tiempo promedio de espera', '8 meses', '2026-09-30', 'Registro del refugio', 7, true, true, null, null, null),
	('pocos-recursos', 'Pocos recursos y pocas manos', 'El cuidado depende de donativos y de voluntarios.', 'hand-coins', 'Voluntarios activos', '12', null, null, 8, true, true, null, null, null);

insert into peludos (id, nombre, especie, descripcion_especie, edad, tamano, descripcion, rasgos, orden, estado, convive_perros, convive_gatos, convive_ninos, es_ejemplo) values
	('luna', 'Luna', 'perro', 'Perrita', '3 años', 'mediano', E'Luna llegó al refugio después de vivir varios meses en la calle, cerca del mercado. Al principio le daba miedo acercarse, pero bastaron unas semanas para que buscara a todos para pedir cariño.\n\nHoy es la más tranquila del patio: le gusta caminar sin prisa, dormir al sol y recargarse en las piernas de quien se siente a su lado.', array['Cariñosa', 'Tranquila']::text[], 1, 'disponible', 'si', 'no_sabemos', 'si', true),
	('canelo', 'Canelo', 'perro', 'Cachorro', '4 meses', 'pequeño', E'Canelo y sus hermanos llegaron en una caja que dejaron en la puerta del refugio. Es el más curioso de la camada y quiere conocer todo lo que se mueve.', array['Juguetón', 'Curioso']::text[], 2, 'disponible', 'si', 'si', 'si', true),
	('miel', 'Miel', 'gato', 'Gata', '1 año', 'pequeño', null, array['Sociable', 'Dormilona']::text[], 3, 'disponible', 'no', 'si', 'no_sabemos', true),
	('rocky', 'Rocky', 'perro', 'Perro', '5 años', 'grande', null, array['Noble', 'Protector']::text[], 4, 'disponible', 'no', 'no', 'no_sabemos', true),
	('nube', 'Nube', 'gato', 'Gatita', '6 meses', 'pequeño', null, array['Juguetona', 'Tierna']::text[], 5, 'disponible', 'no_sabemos', 'si', 'si', true),
	('toby', 'Toby', 'perro', 'Perro', '2 años', 'mediano', null, array['Energético', 'Leal']::text[], 6, 'disponible', 'si', 'no_sabemos', 'no_sabemos', true);

-- Borrador que trajo la sincronización de Facebook (SPEC 15): no sale en el sitio hasta guardarlo en el panel.
insert into peludos (id, nombre, especie, descripcion_especie, edad, tamano, descripcion, rasgos, orden, estado, convive_perros, convive_gatos, convive_ninos, por_revisar, es_ejemplo) values
	('pelusa', 'Pelusa', 'perro', 'Por confirmar', 'Por confirmar', 'pequeño', 'Buscamos hogar para Pelusa, la rescatamos ayer en la carretera a Tenancingo. Es muy dulce y se deja cargar.', array['Por confirmar', 'Por confirmar']::text[], 7, 'disponible', 'no_sabemos', 'no_sabemos', 'no_sabemos', true, true),
	-- Borrador sin foto (SPEC 16): el post solo traía video; el panel no deja publicarlo hasta agregarle una.
	('bombon', 'Bombón', 'perro', 'Perrita chihuahua', 'Por confirmar', 'pequeño', 'Les presentamos a Bombón, una chihuahua que llegó muy asustada. Ya está mejor y busca un hogar paciente.', array['Por confirmar', 'Por confirmar']::text[], 8, 'disponible', 'no_sabemos', 'no_sabemos', 'no_sabemos', true, true);

insert into fotos_peludo (peludo_id, imagen_id, orden) values
	('luna', (select id from imagenes where ruta = 'peludos/luna.jpg'), 1),
	('luna', (select id from imagenes where ruta = 'refugio/patio.jpg'), 2),
	('canelo', (select id from imagenes where ruta = 'peludos/canelo.jpg'), 1),
	('pelusa', (select id from imagenes where ruta = 'peludos/canelo.jpg'), 1);

-- "Su camino en el refugio" (SPEC 13): uno con padrino y otro sin padrino.
insert into hitos_peludo (peludo_id, orden, fecha, tipo, texto, padrino) values
	('luna', 1, '2026-03-12', 'llegada', 'La encontraron cerca del mercado.', null),
	('luna', 2, '2026-04-25', 'esterilizacion', null, 'Familia Ejemplo'),
	('luna', 3, '2026-05-10', 'vacunas', 'Vacuna múltiple y antirrábica.', null),
	('canelo', 1, '2026-07-02', 'llegada', null, null),
	('canelo', 2, '2026-07-20', 'desparasitacion', null, null),
	('miel', 1, '2026-06-15', 'esterilizacion', null, null);

-- "Me gusta" de ejemplo (SPEC 13), para ver el contador en desarrollo.
insert into me_gusta (peludo_id, dispositivo) values
	('luna', '00000000-0000-4000-8000-000000000001'),
	('luna', '00000000-0000-4000-8000-000000000002'),
	('luna', '00000000-0000-4000-8000-000000000003');

insert into campanas (id, fecha, costo, lugar, horario, forma_pago, cupo, estado, es_ejemplo, cartel_id) values
	('2026-09-26', '2026-09-26', 380, 'Refugio Ladridos de Esperanza', 'Desde las 9:30 am aprox.', 'Se paga en el refugio de 11:30 am a 1:30 pm o por transferencia; las cuentas se piden por mensaje. Los lugares no son reembolsables en caso de inasistencia.', null, 'pasada', true, (select id from imagenes where ruta = 'campanas/cartel-2026-09-26.jpg')),
	('2026-10-24', '2026-10-24', 380, 'Refugio Ladridos de Esperanza', 'Desde las 9:30 am aprox.', 'Se paga en el refugio de 11:30 am a 1:30 pm o por transferencia; las cuentas se piden por mensaje. Los lugares no son reembolsables en caso de inasistencia.', 20, 'proxima', true, null);

-- Campaña por revisar (SPEC 15).
insert into campanas (id, fecha, costo, lugar, horario, forma_pago, cupo, estado, por_revisar, es_ejemplo, cartel_id) values
	('2026-11-21', '2026-11-21', 350, 'Explanada de Tenancingo', 'Por confirmar', 'Por confirmar', null, 'proxima', true, true, null);

-- Posts de Facebook ya procesados (SPEC 15): los dos borradores, un aviso de adopción para Rocky y un post incompleto.
insert into publicaciones_facebook (post_id, url_post, pagina, resultado, peludo_id, campana_id, motivo, texto, publicado_en, es_ejemplo) values
	('ejemplo-pelusa', 'https://www.facebook.com/ladridos.esperanza.5/posts/ejemplo-pelusa', 'https://www.facebook.com/ladridos.esperanza.5/', 'peludo', 'pelusa', null, null, 'Buscamos hogar para Pelusa, la rescatamos ayer en la carretera a Tenancingo. Es muy dulce y se deja cargar.', '2026-10-01 18:20:00+00', true),
	('ejemplo-campana', 'https://www.facebook.com/ladridos.esperanza.5/posts/ejemplo-campana', 'https://www.facebook.com/ladridos.esperanza.5/', 'campana', null, '2026-11-21', null, 'Campaña de esterilización el sábado 21 de noviembre en la explanada de Tenancingo. Cuota de recuperación $350.', '2026-10-01 20:00:00+00', true),
	('ejemplo-rocky', 'https://www.facebook.com/ladridos.esperanza.5/posts/ejemplo-rocky', 'https://www.facebook.com/ladridos.esperanza.5/', 'adoptado', 'rocky', null, null, '¡Rocky ya tiene familia! Gracias a todos los que compartieron.', '2026-10-02 01:00:00+00', true),
	('ejemplo-incompleto', 'https://www.facebook.com/p/Sos-Ladridos-de-Esperanza-Tenancingo-100067644922613/posts/ejemplo-incompleto', 'https://www.facebook.com/p/Sos-Ladridos-de-Esperanza-Tenancingo-100067644922613/', 'incompleto', null, null, 'sin_nombre', 'Esta bebé necesita hogar urgente, se entrega desparasitada.', '2026-10-02 02:00:00+00', true),
	('ejemplo-bombon', 'https://www.facebook.com/reel/ejemplo-bombon/', 'https://www.facebook.com/ladridos.esperanza.5/', 'peludo', 'bombon', null, null, 'Les presentamos a Bombón, una chihuahua que llegó muy asustada. Ya está mejor y busca un hogar paciente.', '2026-10-02 03:00:00+00', true),
	('ejemplo-necesidad', 'https://www.facebook.com/ladridos.esperanza.5/posts/ejemplo-necesidad', 'https://www.facebook.com/ladridos.esperanza.5/', 'necesidad', null, null, null, 'Buenas noches, amigos: necesitamos sobres o latas para los michis y también arena. ¡Gracias!', '2026-10-02 04:00:00+00', true);

insert into necesidades (id, tipo, descripcion, urgencia, fecha_vigencia, es_ejemplo) values
	('croquetas', 'alimento', 'Croquetas', 'urgente', '2026-11-30', true),
	('medicinas', 'medicina', 'Medicinas', 'necesaria', '2026-11-30', true),
	('cobijas', 'cobijas', 'Cobijas', 'necesaria', '2026-11-30', true);

-- Borradores de necesidad que trajo un post de Facebook (SPEC 16).
insert into necesidades (id, tipo, descripcion, urgencia, fecha_vigencia, por_revisar, publicacion_id, es_ejemplo) values
	('alimento-2026-11-01', 'alimento', 'Sobres o latas para gatos', 'necesaria', '2026-11-01', true, (select id from publicaciones_facebook where post_id = 'ejemplo-necesidad'), true),
	('limpieza-2026-11-01', 'limpieza', 'Arena para gatos', 'necesaria', '2026-11-01', true, (select id from publicaciones_facebook where post_id = 'ejemplo-necesidad'), true);

insert into destinos_donativo (id, destino, cubre, monto, equivalencia, orden, es_ejemplo) values
	('alimento', 'Alimento', 'Comida diaria de los animales', 200, 'un día de comida para 10 perros', 1, true),
	('atencion-veterinaria', 'Atención veterinaria', 'Vacunas, desparasitación, medicinas y urgencias', 350, 'vacuna y desparasitación', 2, true),
	('esterilizaciones', 'Esterilizaciones', 'Campañas y apoyo a familias', 380, 'una esterilización', 3, true),
	('rescates-y-traslados', 'Rescates y traslados', 'Transporte y primeros auxilios', 150, 'un traslado de rescate', 4, true),
	('espacio-y-cuidado', 'Espacio y cuidado', 'Limpieza, reparaciones y camas', 100, 'limpieza de una semana', 5, true);

insert into negocios (id, nombre, categoria_id, descripcion_corta, logo_id, direccion, latitud, longitud, whatsapp, estado, porcentaje_aporte, fecha_alta, es_ejemplo) values
	('cafe-del-jardin', 'Café del Jardín', 'cafeterias', 'Desayunos, antojitos, pasteles hechos en casa y café', null, 'Calle Hidalgo 12, Centro, Tenancingo (ejemplo)', null, null, null, 'publicado', 5, '2026-10-01', true),
	('la-cocina-de-dona-mary', 'La Cocina de Doña Mary', 'comida-corrida', 'Comida casera de lunes a sábado', null, 'Calle Morelos 210 (ejemplo)', null, null, null, 'publicado', 4, '2026-10-01', true),
	('panaderia-san-juan', 'Panadería San Juan', 'panaderias', 'Pan de horno de piedra desde 1978', null, 'Plaza Principal 8 (ejemplo)', null, null, null, 'publicado', 3, '2026-10-01', true),
	('pizzeria-nonna-lupe', 'Pizzería Nonna Lupe', 'pizzas', 'Pizza delgada al horno de leña', null, 'Av. Las Torres 312 (ejemplo)', null, null, null, 'publicado', 5, '2026-10-01', true),
	('tacos-don-chuy', 'Tacos Don Chuy', 'taquerias', 'Tacos al pastor con trompo de leña', null, 'Av. Juárez 45 (ejemplo)', 18.9608, -99.5906, '5215500000001', 'publicado', 5, '2026-10-01', true);

insert into promociones (negocio_id, texto, fecha_inicio, fecha_fin) values
	('cafe-del-jardin', '2x1 en café americano de 4 a 6 pm', '2026-10-01', null),
	('la-cocina-de-dona-mary', 'Comida corrida con agua del día por $85', '2026-09-01', '2026-09-30'),
	('panaderia-san-juan', 'Lleva 10 piezas de pan y te regalamos 2', '2026-10-01', null),
	('pizzeria-nonna-lupe', 'Martes de pizza mediana por $120', '2026-10-01', null),
	('tacos-don-chuy', 'Orden de 5 tacos con refresco por $95', '2026-10-01', null);

insert into horarios (negocio_id, dia, cerrado) values
	('cafe-del-jardin', 'lun', false),
	('cafe-del-jardin', 'mar', false),
	('cafe-del-jardin', 'mie', false),
	('cafe-del-jardin', 'jue', false),
	('cafe-del-jardin', 'vie', false),
	('cafe-del-jardin', 'sab', false),
	('cafe-del-jardin', 'dom', false),
	('la-cocina-de-dona-mary', 'lun', false),
	('la-cocina-de-dona-mary', 'mar', false),
	('la-cocina-de-dona-mary', 'mie', false),
	('la-cocina-de-dona-mary', 'jue', false),
	('la-cocina-de-dona-mary', 'vie', false),
	('la-cocina-de-dona-mary', 'sab', false),
	('la-cocina-de-dona-mary', 'dom', true),
	('panaderia-san-juan', 'lun', false),
	('panaderia-san-juan', 'mar', false),
	('panaderia-san-juan', 'mie', false),
	('panaderia-san-juan', 'jue', false),
	('panaderia-san-juan', 'vie', false),
	('panaderia-san-juan', 'sab', false),
	('pizzeria-nonna-lupe', 'lun', false),
	('pizzeria-nonna-lupe', 'mar', false),
	('pizzeria-nonna-lupe', 'mie', false),
	('pizzeria-nonna-lupe', 'jue', false),
	('pizzeria-nonna-lupe', 'vie', false),
	('pizzeria-nonna-lupe', 'sab', false),
	('pizzeria-nonna-lupe', 'dom', false),
	('tacos-don-chuy', 'lun', false),
	('tacos-don-chuy', 'mar', false),
	('tacos-don-chuy', 'mie', false),
	('tacos-don-chuy', 'jue', false),
	('tacos-don-chuy', 'vie', false),
	('tacos-don-chuy', 'sab', false),
	('tacos-don-chuy', 'dom', true);

insert into turnos (negocio_id, dia, abre, cierra, orden) values
	('cafe-del-jardin', 'lun', '08:00', '21:00', 1),
	('cafe-del-jardin', 'mar', '08:00', '21:00', 1),
	('cafe-del-jardin', 'mie', '08:00', '21:00', 1),
	('cafe-del-jardin', 'jue', '08:00', '21:00', 1),
	('cafe-del-jardin', 'vie', '08:00', '21:00', 1),
	('cafe-del-jardin', 'sab', '08:00', '21:00', 1),
	('cafe-del-jardin', 'dom', '09:00', '13:00', 1),
	('cafe-del-jardin', 'dom', '17:00', '20:00', 2),
	('la-cocina-de-dona-mary', 'lun', '13:00', '17:30', 1),
	('la-cocina-de-dona-mary', 'mar', '13:00', '17:30', 1),
	('la-cocina-de-dona-mary', 'mie', '13:00', '17:30', 1),
	('la-cocina-de-dona-mary', 'jue', '13:00', '17:30', 1),
	('la-cocina-de-dona-mary', 'vie', '13:00', '17:30', 1),
	('la-cocina-de-dona-mary', 'sab', '13:00', '17:00', 1),
	('panaderia-san-juan', 'lun', '07:00', '20:00', 1),
	('panaderia-san-juan', 'mar', '07:00', '20:00', 1),
	('panaderia-san-juan', 'mie', '07:00', '20:00', 1),
	('panaderia-san-juan', 'jue', '07:00', '20:00', 1),
	('panaderia-san-juan', 'vie', '07:00', '20:00', 1),
	('panaderia-san-juan', 'sab', '07:00', '20:00', 1),
	('pizzeria-nonna-lupe', 'lun', '14:00', '22:30', 1),
	('pizzeria-nonna-lupe', 'mar', '14:00', '22:30', 1),
	('pizzeria-nonna-lupe', 'mie', '14:00', '22:30', 1),
	('pizzeria-nonna-lupe', 'jue', '14:00', '22:30', 1),
	('pizzeria-nonna-lupe', 'vie', '14:00', '22:30', 1),
	('pizzeria-nonna-lupe', 'sab', '14:00', '23:30', 1),
	('pizzeria-nonna-lupe', 'dom', '14:00', '21:00', 1),
	('tacos-don-chuy', 'lun', '13:00', '23:30', 1),
	('tacos-don-chuy', 'mar', '13:00', '23:30', 1),
	('tacos-don-chuy', 'mie', '13:00', '23:30', 1),
	('tacos-don-chuy', 'jue', '13:00', '23:30', 1),
	('tacos-don-chuy', 'vie', '13:00', '23:30', 1),
	('tacos-don-chuy', 'sab', '13:00', '00:30', 1);

insert into grupos_menu (id, negocio_id, nombre, orden) overriding system value values
	(1, 'cafe-del-jardin', 'Desayunos', 1),
	(2, 'cafe-del-jardin', 'De antojo', 2),
	(3, 'cafe-del-jardin', 'Sándwiches', 3),
	(4, 'cafe-del-jardin', 'Lo dulce', 4),
	(5, 'cafe-del-jardin', 'Café', 5),
	(6, 'cafe-del-jardin', 'Sin café', 6),
	(7, 'cafe-del-jardin', 'Té', 7),
	(8, 'la-cocina-de-dona-mary', 'Menú', 1),
	(9, 'panaderia-san-juan', 'Menú', 1),
	(10, 'pizzeria-nonna-lupe', 'Menú', 1),
	(11, 'tacos-don-chuy', 'Menú', 1);

insert into secciones_menu (id, grupo_id, nombre, nota, orden) overriding system value values
	(1, 1, 'Desayunos', 'Disponibles de 8:00 am a 1:00 pm', 1),
	(2, 1, 'Bebidas y algo más', null, 2),
	(3, 1, 'Paquete desayuno', 'En la compra de un desayuno', 3),
	(4, 1, 'Extras', null, 4),
	(5, 2, 'Antojitos', null, 1),
	(6, 2, 'Molletes', null, 2),
	(7, 2, 'Para picar', null, 3),
	(8, 2, 'Flats', 'Pan delgadito y crujiente', 4),
	(9, 2, 'Ensaladas', null, 5),
	(10, 3, 'Favoritos', 'En baguette o cuernito, con mayonesa, lechuga, jitomate, aguacate, pepino y chile', 1),
	(11, 3, 'Baguettes', null, 2),
	(12, 3, 'Otros sándwiches', null, 3),
	(13, 4, 'Pasteles', 'Hechos en casa, uno a uno y de forma artesanal', 1),
	(14, 4, 'Crepas', 'Con helado +$28', 2),
	(15, 4, 'Pan francés', null, 3),
	(16, 4, 'Helados', null, 4),
	(17, 4, 'Más de lo dulce', null, 5),
	(18, 5, 'Espresso y café', null, 1),
	(19, 5, 'Latte', 'Precio caliente / frío o frappé. Con crema batida +$13', 2),
	(20, 5, 'Cappuccino', 'Precio caliente / frío o frappé', 3),
	(21, 5, 'Mocha', 'Precio caliente / frío o frappé', 4),
	(22, 6, 'Frappé de frutas', 'Con poppings +$20', 1),
	(23, 6, 'Limonadas', null, 2),
	(24, 6, 'Malteadas', null, 3),
	(25, 6, 'Chocolate caliente', 'Leche cremosita con sabor y crema batida', 4),
	(26, 6, 'Creams', 'Precio caliente / frío o frappé. Con tapioca +$30', 5),
	(27, 6, 'Otros', null, 6),
	(28, 7, 'Infusiones', '$50, caliente o frío', 1),
	(29, 7, 'Chai latte', 'Té negro, leche y especias. Precio caliente / frío o frappé. Con tapioca +$30', 2),
	(30, 7, 'Fraté', 'Tisana frappé. Con poppings +$20', 3),
	(31, 7, 'Té latte', 'Precio caliente / frío o frappé. Con tapioca +$30', 4),
	(32, 8, 'Menú del día', null, 1),
	(33, 9, 'Pan', null, 1),
	(34, 10, 'Pizzas (mediana)', null, 1),
	(35, 11, 'Tacos', null, 1);

insert into platillos (id, seccion_id, nombre, descripcion, es_extra, disponible, orden) overriding system value values
	(1, 1, 'Restaurador', 'Chilaquiles verdes o rojos con pollo o chorizo. Gratinados +$15, huevo estrellado +$12', false, true, 1),
	(2, 1, 'Enchiladas', 'Verdes o rojas con pollo o chorizo', false, true, 2),
	(3, 1, 'Enchiladas Suizas', 'Verdes con pollo', false, true, 3),
	(4, 1, 'De la Granja', 'Huevos al gusto con frijoles refritos y totopos', false, true, 4),
	(5, 1, 'Mañanero', 'Cuernito calientito con huevo revuelto y queso gratinado. Jamón +$15, tocino o chorizo +$28', false, true, 5),
	(6, 1, 'Estudiante', 'Molletes. Jamón +$15, tocino, chorizo o pollo +$28', false, true, 6),
	(7, 1, 'Especial Latte', 'Dos huevos estrellados sobre tortilla doradita con frijoles, jamón y queso, con rajas poblanas y salsa ranchera', false, true, 7),
	(8, 1, 'Omelet Poblano', 'Relleno de rajas poblanas, bañado en salsa de queso', false, true, 8),
	(9, 1, 'Omelet Campesino', 'Relleno de champiñones, bañado en salsa de queso', false, true, 9),
	(10, 2, 'Mimosa', null, false, true, 1),
	(11, 2, 'Jugo de naranja', null, false, true, 2),
	(12, 2, 'Jugo de arándano', null, false, true, 3),
	(13, 2, 'Jugo de guayaba', null, false, true, 4),
	(14, 2, 'Plato de papaya con yogurt y granola', null, false, true, 5),
	(15, 2, 'Copa de yoghurt con frutos rojos y granola', null, false, true, 6),
	(16, 3, 'Paquete desayuno', 'Café americano, tisana de manzanilla o limón, jugo o fruta y una pieza de pan con mantequilla y mermelada. Por $20 más cambia tu café americano por café de olla, latte clásico, cappuccino clásico o chocolate caliente', true, true, 1),
	(17, 4, 'Huevo', null, true, true, 1),
	(18, 4, 'Jamón', null, true, true, 2),
	(19, 4, 'Pollo, chorizo o tocino', null, true, true, 3),
	(20, 5, 'Enchiladas', 'Verdes o rojas con pollo o chorizo', false, true, 1),
	(21, 5, 'Enchiladas Suizas', 'Verdes con pollo y gratinadas', false, true, 2),
	(22, 5, 'Enmoladas', 'Mole rojo de Teco rellenas de pollo', false, true, 3),
	(23, 5, 'Chilaquiles', 'Verdes o rojos con pollo o chorizo', false, true, 4),
	(24, 5, 'Tacos dorados de pollo (3 pzas)', null, false, true, 5),
	(25, 5, 'Tostadas de pollo (2 pzas)', null, false, true, 6),
	(26, 5, 'Tostadas de cochinita pibil (2 pzas)', null, false, true, 7),
	(27, 6, 'Clásicos', null, false, true, 1),
	(28, 6, 'Con jamón', null, false, true, 2),
	(29, 6, 'Con tocino', null, false, true, 3),
	(30, 6, 'Con pollo', null, false, true, 4),
	(31, 6, 'Con chorizo', null, false, true, 5),
	(32, 6, 'Mollepizza', 'Bolillo con salsa italiana, pepperoni y queso gratinado', false, true, 6),
	(33, 7, 'Hamburguesa de pollo con papas', null, false, true, 1),
	(34, 7, 'Hamburguesa básica de res', 'Pan brioche, carne de res, queso, jitomate, lechuga, pepinillos y cebolla, con papas. Carne extra +$70, tocino +$28', false, true, 2),
	(35, 7, 'Nuggets de pollo con papas', null, false, true, 3),
	(36, 7, 'Papas a la francesa', null, false, true, 4),
	(37, 7, 'Palomitas de maíz', null, false, true, 5),
	(38, 8, 'BBQ', 'Pierna deshebrada y queso gratinado', false, true, 1),
	(39, 8, 'Pepperoni', 'Salsa de tomate, pepperoni y queso gratinado', false, true, 2),
	(40, 8, 'Hawaiano', 'Salsa de tomate, jamón, piña y queso gratinado', false, true, 3),
	(41, 9, 'De la casa', 'Lechuga, zanahoria, col, pepino, jitomate y ajonjolí con vinagreta', false, true, 1),
	(42, 9, 'Mexicana', 'De la casa con queso gouda y jamón', false, true, 2),
	(43, 9, 'Japonesa', 'De la casa con atún', false, true, 3),
	(44, 9, 'Kentucky', 'De la casa con tiritas de pechuga asada', false, true, 4),
	(45, 10, 'Jamón de pierna y queso gouda', null, false, true, 1),
	(46, 10, 'Jamón de pavo y queso gouda', null, false, true, 2),
	(47, 10, 'Atún y queso Philadelphia', null, false, true, 3),
	(48, 10, 'Jamón serrano y queso Philadelphia', null, false, true, 4),
	(49, 11, 'Calle Ocho', 'Pierna deshebrada, jamón, queso, mostaza y pepinillos', false, true, 1),
	(50, 11, 'Poblano', 'Queso gouda y rajas poblanas', false, true, 2),
	(51, 11, 'Supremo', 'Ensalada de pollo con manzana, apio y nuez', false, true, 3),
	(52, 11, 'De pollo empanizado', 'Con lechuga, jitomate, pepino, aguacate y chiles', false, true, 4),
	(53, 11, 'De cochinita pibil', 'Con frijoles refritos, cebolla morada y chile habanero', false, true, 5),
	(54, 12, 'Hammy Love', 'Pan blanco, jamón, tocino y queso amarillo gratinado', false, true, 1),
	(55, 12, 'Club Sandwich', 'Pan blanco, mayonesa, jamón, pollo, jitomate y tocino', false, true, 2),
	(56, 13, 'Pastel de queso con zarzamora', 'Base de galleta de canela, crema dulce y mermelada de zarzamora', false, true, 1),
	(57, 13, 'Pastel de zanahoria', 'Con coco, nueces y betún de queso crema', false, true, 2),
	(58, 13, 'Pastel de chocolate', 'Chocolate semiamargo con betún cremoso', false, true, 3),
	(59, 13, 'Strudel de manzana', 'Se sirve calientito. Con helado de vainilla +$28', false, true, 4),
	(60, 13, 'Pastel de coco', 'Bizcocho de coco con betún y coco tostado', false, true, 5),
	(61, 13, 'Cheesecake Tortuga', 'Base de galleta Oreo, dulce de leche y nuez', false, true, 6),
	(62, 13, 'Pastel de blueberry con limón', 'Bizcocho de limón con betún cremoso de limón', false, true, 7),
	(63, 14, 'Nutella', null, false, true, 1),
	(64, 14, 'Cajeta', null, false, true, 2),
	(65, 14, 'Queso con zarzamora', null, false, true, 3),
	(66, 14, 'Queso con guayaba', null, false, true, 4),
	(67, 15, 'Clásico', null, false, true, 1),
	(68, 15, 'Nutella', null, false, true, 2),
	(69, 16, 'Fresa', null, false, true, 1),
	(70, 16, 'Chocolate', null, false, true, 2),
	(71, 16, 'Vainilla', null, false, true, 3),
	(72, 16, 'Galleta Oreo', null, false, true, 4),
	(73, 17, 'Galletas (10 piezas)', null, false, true, 1),
	(74, 17, 'Cuernito doradito con Nutella, cajeta o guayaba', null, false, true, 2),
	(75, 17, 'Cuernito doradito con queso y zarzamora', null, false, true, 3),
	(76, 17, 'Bolillo doradito con Nutella, cajeta o guayaba', null, false, true, 4),
	(77, 17, 'Bolillo doradito con queso y zarzamora', null, false, true, 5),
	(78, 18, 'Espresso corto', null, false, true, 1),
	(79, 18, 'Doppio', null, false, true, 2),
	(80, 18, 'Cortado', 'Con espuma de leche', false, true, 3),
	(81, 18, 'Con panna', 'Con crema batida', false, true, 4),
	(82, 18, 'Affogato', 'Con helado de vainilla', false, true, 5),
	(83, 18, 'Americano', null, false, true, 6),
	(84, 18, 'Americano cortado', null, false, true, 7),
	(85, 18, 'Americano con sabor', null, false, true, 8),
	(86, 18, 'De la olla', null, false, true, 9),
	(87, 18, 'Cold brew', null, false, true, 10),
	(88, 19, 'Clásico', null, false, true, 1),
	(89, 19, 'Sabor', 'Almendra, coco, tiramisú, caramelo, crema irlandesa, menta, rompope, vainilla, amaretto, cajeta o avellana', false, true, 2),
	(90, 20, 'Clásico', null, false, true, 1),
	(91, 20, 'Sabor', null, false, true, 2),
	(92, 21, 'Clásico', null, false, true, 1),
	(93, 21, 'Blanco', null, false, true, 2),
	(94, 21, 'Tortuga', null, false, true, 3),
	(95, 22, 'Fresa', null, false, true, 1),
	(96, 22, 'Mango', null, false, true, 2),
	(97, 22, 'Maracuyá', null, false, true, 3),
	(98, 22, 'Mora azul', null, false, true, 4),
	(99, 22, 'Frutas tropicales', null, false, true, 5),
	(100, 22, 'Fresa kiwi', null, false, true, 6),
	(101, 22, 'Manzana verde', null, false, true, 7),
	(102, 22, 'Fresas con crema', null, false, true, 8),
	(103, 23, 'Pink', null, false, true, 1),
	(104, 23, 'Pasión', null, false, true, 2),
	(105, 23, 'Blue', null, false, true, 3),
	(106, 23, 'Coco', null, false, true, 4),
	(107, 24, 'Fresa', null, false, true, 1),
	(108, 24, 'Chocolate', null, false, true, 2),
	(109, 24, 'Vainilla', null, false, true, 3),
	(110, 24, 'Galleta Oreo', null, false, true, 4),
	(111, 24, 'Nutella', null, false, true, 5),
	(112, 24, 'Cajeta', null, false, true, 6),
	(113, 24, 'Chocomenta', null, false, true, 7),
	(114, 24, 'Chocococo', null, false, true, 8),
	(115, 25, 'Clásico', null, false, true, 1),
	(116, 25, 'Doble chocolate', null, false, true, 2),
	(117, 25, 'Chocolate menta', null, false, true, 3),
	(118, 25, 'Chocolate coco', null, false, true, 4),
	(119, 26, 'Menta', null, false, true, 1),
	(120, 26, 'Coco', null, false, true, 2),
	(121, 26, 'Cajeta', null, false, true, 3),
	(122, 26, 'Nutella', null, false, true, 4),
	(123, 26, 'Mazapán', null, false, true, 5),
	(124, 26, 'Taro', null, false, true, 6),
	(125, 27, 'Naranjada', null, false, true, 1),
	(126, 27, 'Refresco en lata', null, false, true, 2),
	(127, 27, 'Agua embotellada', null, false, true, 3),
	(128, 27, 'Agua mineral', null, false, true, 4),
	(129, 27, 'Agua mineral preparada', null, false, true, 5),
	(130, 28, 'Té verde', 'Sencha, jazmín, chai o menta', false, true, 1),
	(131, 28, 'Té negro', 'Frutos de la pasión, chai o Darjeeling', false, true, 2),
	(132, 28, 'Té rojo Pu Erh', 'Frutos rojos', false, true, 3),
	(133, 28, 'Tisanas herbales', 'Relax, Huracán o manzanilla lavanda', false, true, 4),
	(134, 28, 'Tisanas frutales', 'Mumbai, fresa kiwi, frutos rojos, Bora Bora, jengibre mandarina, Moscú o cereza grosella', false, true, 5),
	(135, 28, 'Tisana rooibos', 'Chai', false, true, 6),
	(136, 29, 'Chai clásico', null, false, true, 1),
	(137, 29, 'Chai masala', null, false, true, 2),
	(138, 29, 'Chai vainilla', null, false, true, 3),
	(139, 29, 'Chai manzana y canela', null, false, true, 4),
	(140, 30, 'Frutos rojos', null, false, true, 1),
	(141, 30, 'Blue Eyes', null, false, true, 2),
	(142, 30, 'Fresa kiwi', null, false, true, 3),
	(143, 30, 'Dragon Blend', null, false, true, 4),
	(144, 31, 'Té verde menta', null, false, true, 1),
	(145, 31, 'Té verde matcha', null, false, true, 2),
	(146, 32, 'Sopa o arroz', null, false, true, 1),
	(147, 32, 'Guisado a elegir', 'Mole, tinga, chiles rellenos', false, true, 2),
	(148, 32, 'Agua fresca', null, false, true, 3),
	(149, 32, 'Postre del día', null, false, false, 4),
	(150, 33, 'Concha', null, false, true, 1),
	(151, 33, 'Oreja', null, false, true, 2),
	(152, 33, 'Cuernito', null, false, true, 3),
	(153, 33, 'Bolillo', null, false, true, 4),
	(154, 34, 'Margarita', null, false, true, 1),
	(155, 34, 'Pepperoni', null, false, true, 2),
	(156, 34, 'Hawaiana', null, false, true, 3),
	(157, 34, 'Limonada', null, false, true, 4),
	(158, 35, 'Pastor', 'Con piña', false, true, 1),
	(159, 35, 'Suadero', null, false, true, 2),
	(160, 35, 'Campechano', null, false, true, 3),
	(161, 35, 'Gringa', null, false, true, 4),
	(162, 35, 'Refresco', null, false, true, 5);

insert into precios (id, platillo_id, etiqueta, monto, texto_alterno, orden) overriding system value values
	(1, 1, null, 90, null, 1),
	(2, 2, null, 90, null, 1),
	(3, 3, null, 100, null, 1),
	(4, 4, null, 90, null, 1),
	(5, 5, null, 85, null, 1),
	(6, 6, null, 65, null, 1),
	(7, 7, null, 115, null, 1),
	(8, 8, null, 110, null, 1),
	(9, 9, null, 110, null, 1),
	(10, 10, null, 49, null, 1),
	(11, 11, null, 38, null, 1),
	(12, 12, null, 38, null, 1),
	(13, 13, null, 38, null, 1),
	(14, 14, null, 45, null, 1),
	(15, 15, null, 58, null, 1),
	(16, 16, null, 60, null, 1),
	(17, 17, null, 12, null, 1),
	(18, 18, null, 15, null, 1),
	(19, 19, null, 28, null, 1),
	(20, 20, null, 90, null, 1),
	(21, 21, null, 100, null, 1),
	(22, 22, null, 110, null, 1),
	(23, 23, null, 90, null, 1),
	(24, 24, null, 70, null, 1),
	(25, 25, null, 75, null, 1),
	(26, 26, null, 105, null, 1),
	(27, 27, null, 65, null, 1),
	(28, 28, null, 80, null, 1),
	(29, 29, null, 93, null, 1),
	(30, 30, null, 93, null, 1),
	(31, 31, null, 93, null, 1),
	(32, 32, null, 85, null, 1),
	(33, 33, null, 78, null, 1),
	(34, 34, null, 175, null, 1),
	(35, 35, null, 69, null, 1),
	(36, 36, null, 55, null, 1),
	(37, 37, null, 40, null, 1),
	(38, 38, null, 79, null, 1),
	(39, 39, null, 79, null, 1),
	(40, 40, null, 79, null, 1),
	(41, 41, null, 80, null, 1),
	(42, 42, null, 100, null, 1),
	(43, 43, null, 100, null, 1),
	(44, 44, null, 120, null, 1),
	(45, 45, null, 75, null, 1),
	(46, 46, null, 75, null, 1),
	(47, 47, null, 90, null, 1),
	(48, 48, null, 95, null, 1),
	(49, 49, null, 100, null, 1),
	(50, 50, null, 80, null, 1),
	(51, 51, null, 90, null, 1),
	(52, 52, null, 105, null, 1),
	(53, 53, null, 105, null, 1),
	(54, 54, null, 100, null, 1),
	(55, 55, null, 110, null, 1),
	(56, 56, null, 65, null, 1),
	(57, 57, null, 65, null, 1),
	(58, 58, null, 65, null, 1),
	(59, 59, null, 65, null, 1),
	(60, 60, null, 65, null, 1),
	(61, 61, null, 68, null, 1),
	(62, 62, null, 70, null, 1),
	(63, 63, null, 75, null, 1),
	(64, 64, null, 75, null, 1),
	(65, 65, null, 75, null, 1),
	(66, 66, null, 75, null, 1),
	(67, 67, null, 53, null, 1),
	(68, 68, null, 58, null, 1),
	(69, 69, null, 53, null, 1),
	(70, 70, null, 53, null, 1),
	(71, 71, null, 53, null, 1),
	(72, 72, null, 53, null, 1),
	(73, 73, null, 28, null, 1),
	(74, 74, null, 45, null, 1),
	(75, 75, null, 50, null, 1),
	(76, 76, null, 41, null, 1),
	(77, 77, null, 46, null, 1),
	(78, 78, null, 35, null, 1),
	(79, 79, null, 46, null, 1),
	(80, 80, null, 40, null, 1),
	(81, 81, null, 42, null, 1),
	(82, 82, null, 60, null, 1),
	(83, 83, null, 35, null, 1),
	(84, 84, null, 40, null, 1),
	(85, 85, null, 47, null, 1),
	(86, 86, null, 40, null, 1),
	(87, 87, null, 50, null, 1),
	(88, 88, 'Caliente', 49, null, 1),
	(89, 88, 'Frío o frappé', 59, null, 2),
	(90, 89, 'Caliente', 54, null, 1),
	(91, 89, 'Frío o frappé', 64, null, 2),
	(92, 90, 'Caliente', 49, null, 1),
	(93, 90, 'Frío o frappé', 59, null, 2),
	(94, 91, 'Caliente', 54, null, 1),
	(95, 91, 'Frío o frappé', 64, null, 2),
	(96, 92, 'Caliente', 56, null, 1),
	(97, 92, 'Frío o frappé', 66, null, 2),
	(98, 93, 'Caliente', 60, null, 1),
	(99, 93, 'Frío o frappé', 68, null, 2),
	(100, 94, 'Caliente', 60, null, 1),
	(101, 94, 'Frío o frappé', 68, null, 2),
	(102, 95, null, 63, null, 1),
	(103, 96, null, 63, null, 1),
	(104, 97, null, 63, null, 1),
	(105, 98, null, 63, null, 1),
	(106, 99, null, 63, null, 1),
	(107, 100, null, 63, null, 1),
	(108, 101, null, 63, null, 1),
	(109, 102, null, 63, null, 1),
	(110, 103, null, 45, null, 1),
	(111, 104, null, 45, null, 1),
	(112, 105, null, 45, null, 1),
	(113, 106, null, 50, null, 1),
	(114, 107, null, 49, null, 1),
	(115, 108, null, 49, null, 1),
	(116, 109, null, 49, null, 1),
	(117, 110, null, 52, null, 1),
	(118, 111, null, 52, null, 1),
	(119, 112, null, 52, null, 1),
	(120, 113, null, 52, null, 1),
	(121, 114, null, 52, null, 1),
	(122, 115, null, 55, null, 1),
	(123, 116, null, 60, null, 1),
	(124, 117, null, 60, null, 1),
	(125, 118, null, 60, null, 1),
	(126, 119, 'Caliente', 54, null, 1),
	(127, 119, 'Frío o frappé', 64, null, 2),
	(128, 120, 'Caliente', 54, null, 1),
	(129, 120, 'Frío o frappé', 64, null, 2),
	(130, 121, 'Caliente', 54, null, 1),
	(131, 121, 'Frío o frappé', 64, null, 2),
	(132, 122, 'Caliente', 54, null, 1),
	(133, 122, 'Frío o frappé', 64, null, 2),
	(134, 123, 'Caliente', 54, null, 1),
	(135, 123, 'Frío o frappé', 64, null, 2),
	(136, 124, 'Caliente', 60, null, 1),
	(137, 124, 'Frío o frappé', 70, null, 2),
	(138, 125, null, 45, null, 1),
	(139, 126, null, 35, null, 1),
	(140, 127, null, 28, null, 1),
	(141, 128, null, 39, null, 1),
	(142, 129, null, 45, null, 1),
	(143, 130, null, 50, null, 1),
	(144, 131, null, 50, null, 1),
	(145, 132, null, 50, null, 1),
	(146, 133, null, 50, null, 1),
	(147, 134, null, 50, null, 1),
	(148, 135, null, 50, null, 1),
	(149, 136, 'Caliente', 54, null, 1),
	(150, 136, 'Frío o frappé', 64, null, 2),
	(151, 137, 'Caliente', 54, null, 1),
	(152, 137, 'Frío o frappé', 64, null, 2),
	(153, 138, 'Caliente', 54, null, 1),
	(154, 138, 'Frío o frappé', 64, null, 2),
	(155, 139, 'Caliente', 54, null, 1),
	(156, 139, 'Frío o frappé', 64, null, 2),
	(157, 140, null, 65, null, 1),
	(158, 141, null, 65, null, 1),
	(159, 142, null, 65, null, 1),
	(160, 143, null, 65, null, 1),
	(161, 144, 'Caliente', 54, null, 1),
	(162, 144, 'Frío o frappé', 64, null, 2),
	(163, 145, 'Caliente', 66, null, 1),
	(164, 145, 'Frío o frappé', 76, null, 2),
	(165, 146, null, null, 'Incluido', 1),
	(166, 147, null, 85, null, 1),
	(167, 148, null, null, 'Incluido', 1),
	(168, 149, null, 25, null, 1),
	(169, 150, null, 12, null, 1),
	(170, 151, null, 14, null, 1),
	(171, 152, null, 13, null, 1),
	(172, 153, null, 4, null, 1),
	(173, 154, null, 140, null, 1),
	(174, 155, null, 165, null, 1),
	(175, 156, null, 160, null, 1),
	(176, 157, null, 35, null, 1),
	(177, 158, null, 18, null, 1),
	(178, 159, null, 20, null, 1),
	(179, 160, null, 22, null, 1),
	(180, 161, null, 45, null, 1),
	(181, 162, null, 22, null, 1);

select setval(pg_get_serial_sequence('turnos', 'id'), coalesce((select max(id) from turnos), 1));
select setval(pg_get_serial_sequence('grupos_menu', 'id'), coalesce((select max(id) from grupos_menu), 1));
select setval(pg_get_serial_sequence('secciones_menu', 'id'), coalesce((select max(id) from secciones_menu), 1));
select setval(pg_get_serial_sequence('platillos', 'id'), coalesce((select max(id) from platillos), 1));
select setval(pg_get_serial_sequence('precios', 'id'), coalesce((select max(id) from precios), 1));

-- Solicitudes de ejemplo del formulario Súmate (SPEC 07); la bandeja del panel las marca como "Ejemplo".
insert into solicitudes_negocio (nombre_negocio, tipo, whatsapp, nombre_contacto, mensaje, acepto_aviso, estado, creada_en, actualizada_en, es_ejemplo) values
	('Nevería La Esquina', 'Nevería', '7141000001', 'Rosa', 'Vendemos nieves de garrafa en el centro. ¿Cómo nos sumamos?', true, 'nueva', now() - interval '2 hours', null, true),
	('Fonda Doña Mary', 'Comida corrida', '7141000002', null, null, true, 'contactada', now() - interval '3 days', now() - interval '2 days', true),
	('Tienda de regalos Sol', 'Regalos y detalles', '7141000003', 'Julio', 'Queremos apoyar al refugio.', true, 'descartada', now() - interval '10 days', now() - interval '9 days', true);
